import { CourseView } from "@/sections/course/view/course-view"

export async function generateMetaData() {
    return {
        title: 'Home',
        description: 'Generated by create next app',
    }
}

export default function Page() {
    return <CourseView />
}