import DashboardView from "@/sections/dashboard/view/dashboard-view"


export async function generateMetaData() {
    return {
        title: 'Home',
        description: 'Generated by create next app',
    }
}

export default function Page(){
    return <DashboardView />
}